class Person < ActiveRecord::Base
	def payment_amount
		if household == 1 && income < 11670
			 self.name + ", your payment will be $25"
		elsif household == 1 && income < 14588
			 self.name + ", your payment will be $60"
		elsif household == 1 && income < 17505
			 self.name + ", your payment will be $75"
		elsif household == 1 && income < 20423
			 self.name + ", your payment will be $100"
		elsif household == 1 && income < 23340
			 self.name + ", your payment will be $150"
		elsif household == 1 && income > 23340
			 self.name + ", your payment will be $200"
		elsif household == 2 && income < 15730
			 self.name + ", your payment will be $25"
		elsif household == 2 && income < 19663
			 self.name + ", your payment will be $60"
		elsif household == 2 && income < 23595
			 self.name + ", your payment will be $75"
		elsif household == 2 && income < 27528
			 self.name + ", your payment will be $100"
		elsif household == 2 && income < 31460
			 self.name + ", your payment will be $150"
		elsif household == 2 && income > 31460
			 self.name + ", your payment will be $200"
		elsif household == 3 && income < 19790
			 self.name + ", your payment will be $25"
		elsif household == 3 && income < 24738
			 self.name + ", your payment will be $60"
		elsif household == 3 && income < 19685
			 self.name + ", your payment will be $75"
		elsif household == 3 && income < 34633
			 self.name + ", your payment will be $100"
		elsif household == 3 && income < 39580
			 self.name + ", your payment will be $150"
		elsif household == 3 && income > 39580
			 self.name + ", your payment will be $200"
		elsif household == 4 && income < 23850
			 self.name + ", your payment will be $25"
		elsif household == 4 && income < 29813
			 self.name + ", your payment will be $60"
		elsif household == 4 && income < 35775
			 self.name + ", your payment will be $75"
		elsif household == 4 && income < 41738
			 self.name + ", your payment will be $100"
		elsif household == 4 && income < 47700
			 self.name + ", your payment will be $150"
		elsif household == 4 && income > 47700
			 self.name + ", your payment will be $200"
		elsif household == 5 && income < 27910
			 self.name + ", your payment will be $25"
		elsif household == 5 && income < 34888
			 self.name + ", your payment will be $60"
		elsif household == 5 && income < 41865
			 self.name + ", your payment will be $75"
		elsif household == 5 && income < 48843
			 self.name + ", your payment will be $100"
		elsif household == 5 && income < 55820
			 self.name + ", your payment will be $150"
		elsif household == 5 && income > 55820
			 self.name + ", your payment will be $200"
		elsif household == 6 && income < 31970
			 self.name + ", your payment will be $25"
		elsif household == 6 && income < 39963
			 self.name + ", your payment will be $60"
		elsif household == 6 && income < 47955
			 self.name + ", your payment will be $75"
		elsif household == 6 && income < 55984
			 self.name + ", your payment will be $100"
		elsif household == 6 && income < 63940
			 self.name + ", your payment will be $150"
		elsif household == 6 && income > 63941
			 self.name + ", your payment will be $200"
		elsif household == 7 && income < 36030
			 self.name + ", your payment will be $25"
		elsif household == 7 && income < 145038
			 self.name + ", your payment will be $60"
		elsif household == 7 && income < 54045
			 self.name + ", your payment will be $75"
		elsif household == 7 && income < 63053
			 self.name + ", your payment will be $100"
		elsif household == 7 && income < 72060
			 self.name + ", your payment will be $150"
		elsif household == 7 && income > 72060
			 self.name + ", your payment will be $200"
		elsif household == 8 && income < 40090
			 self.name + ", your payment will be $25"
		elsif household == 8 && income < 50113
			 self.name + ", your payment will be $60"
		elsif household == 8 && income < 60135
			 self.name + ", your payment will be $75"
		elsif household == 8 && income < 70158
			 self.name + ", your payment will be $100"
		elsif household == 8 && income < 80180
			 self.name + ", your payment will be $150"
		elsif household == 8 && income > 80180
			 self.name + ", your payment will be $200"
		elsif household > 8
			 self.name + ", your payment will be $25"
		end
	end
end
